Add files via upload
karolukasik/Java-various-exercises pull request #1
Opened 2023-03-23 09:01 UTC by karolukasik

PeselNumber class

2023-03-27 10:09 UTC, Jonarzz requested changes

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/Main.java
> +public class Main {
zbędne - do wyrzucenia

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/pom.xml
> +        <maven.compiler.target>11</maven.compiler.target>
JDK11 ma 4,5 roku już - używaj bieżącej wersji (obecnie 20)

dzięki temu możesz np. skorzystać z `record`ów

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumber.java
> +        boolean areRulesFulfilled = true;
do czego służy ta zmienna, skoro nie zmienia swojej wartości? nie różni się to od `return true`

z kolei skoro zawsze zwracane jest `true`, które i tak nie jest wykorzystywane, a w przypadku błędu walidacji leci wyjątek - po co zwracać cokolwiek?

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumber.java
> +            if (!rule.applyRule(pesel)) {
`if (!rule.applyRule(pesel))` vs `if (rule.notValidFor(pesel))` / `if (rule.isNotMetBy(pesel))`

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumber.java
> +    public String extractSex() {
jak masz to już na zewnątrz, to można byłoby przekazywać strategię wyciągania do metody, np. tak: `public String extractUsing(DataExtractor extractor)`, wtedy użycie wyglądałoby tak: `pesel.extractUsing(SEX_DECODER)` albo po zmianie nazw w enumie: `pesel.extract(SEX)`, `pesel.extract(BIRTH_DATE)`

obecnie przy dodawaniu kolejnej strategii, trzeba dodać też metodę tutaj

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselDecoder.java
> +        public String extract(String encodedData) {
doceniam możliwość zwrócenia dowolnej płci, ale jednak lepiej byłoby to zawrzeć w enumie, nawet jeśli byłoby tam dużo wartości, to klient API od razu wie, co dostanie w zwrotce

jaką wartosć ma `sex` w poniższym kodzie Twoim zdaniem, bez dodatkowego kontekstu? wielkie czy małe litery? w jakim języku? ;) 
`String sex = pesel.getSex()`

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselDecoder.java
> +            } else {
`else` po returnie jest zbędny - można wypłaszczyć:

```java
if (...) {
    return 1;
}
return 0;
```

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselDecoder.java
> +            return date.format(formatter);
klient API musi się domyślać, jaki foramt dostanie albo dekompilować bibliotekę - jak wyciągana jest data, to powinien być zwrócony typ daty, ew. powinien być przyjmowany formatter i wtedy zwracany string

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselDecoder.java
> +            var date = LocalDate.of(birthYearNumber, birthMonthNumber, birthDayNumber);
https://www.youtube.com/watch?v=zsfEWLGgsEY

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/util/StringUtils.java
> +        return Integer.parseInt(String.valueOf(from.charAt(index)));
https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#getNumericValue(char)

w ramach ciekawostki polecam https://www.youtube.com/watch?v=QIEpZ0MGoBc

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/util/StringUtils.java
> +        return 10 * decimalNumber + onesNumber;
czy mi się wydaje, czy ta skomplikowana logika to `value.substring(from, to + 1)` + `Integer.parseInt`? :p

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +            return pesel.matches("^[0-9]*$");
`^[0-9]{11}$` opędzluje 2 reguły jednocześnie

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +    private static boolean peselCorrectnessEquation(String pesel) {
`peselCorrectnessEquation` brzmi jak nazwa pola albo stałej, a nie metody

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +    private static int multiplyByWeightAndExtractOnesDigit(int i, int digit) {
i = index?

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +        for (int i = 9; i >= 0; i--) {
ma to znaczenie, że nie jest od 0, tylko w drugą stronę?

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +        if (multiplicationResult > 10) {
ten if-else to to samo co `return multiplicationResult % 10`

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/test/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberTest.java
> +        Exception ex = assertThrows(IllegalArgumentException.class, methodToExecute);
`assertThrows` lepiej pasuje do bloku "then" (analogicznie w pozostałych metodach)

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/test/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberTest.java
> +    @ValueSource(strings = {"2", "123456789123"})
warto byłoby dodać string o długości 10 jako edge case albo `@MethodSource` + `IntStream.concat` + `IntStream.rangeClosed` i sprawdzić wszystkie o długościach od 1 np. do 20 z wyłączeniem 11

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/test/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberTest.java
> +        boolean applyingRuleResult = rule.applyRule(value);
bloki given i when do rozdzielenia

2023-03-27 10:09 UTC, Jonarzz commented on class-practice/src/test/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberTest.java
> +    public void applyRuleMethodReturnsTrueForStringOfLengthEleven(String value) {
te testy `PeselNumberRule` powinny być w oddzielnej klasie

2023-04-12 16:50 UTC, karolukasik commented on class-practice/src/main/java/com/karolina/Main.java
> +public class Main {
W sensie nie commitować tej klasy Main czy przenieść metodę main gdzieś do innej klasy?

2023-04-12 19:32 UTC, karolukasik commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumber.java
> +    public String extractSex() {
Zrobione, ale niezgodne z wymogami zadania :P

2023-04-12 19:59 UTC, karolukasik commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +            return pesel.matches("^[0-9]*$");
I agree, ale czy warto łączyć dwie reguły w jedną? Zamysł był taki żeby jednak je rozdzielić

2023-04-12 20:08 UTC, karolukasik commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +        for (int i = 9; i >= 0; i--) {
Nie ma znaczenia, miało kiedyś ale zmieniłam koncepcję :D Zmienione po bożemu

2023-04-12 20:09 UTC, karolukasik commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +    private static int multiplyByWeightAndExtractOnesDigit(int i, int digit) {
Si, zmienione

2023-04-12 20:10 UTC, karolukasik commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +        if (multiplicationResult > 10) {
No nie, bo.... a jednak tak

2023-04-13 04:45 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/Main.java
> +public class Main {
nie commitować - kod weryfikujesz testami, a jest on de facto biblioteką klas do wykorzystania w ramach innego kodu, sam w sobie nic nie robi i nie ma sensu go "uruchamiać"

2023-04-13 04:46 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumber.java
> +    public String extractSex() {
zadanie nie przewidywało strategii, a jak już są, to warto z nich korzystać elastycznie :p

2023-04-13 05:20 UTC, Jonarzz commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/PeselNumberRule.java
> +            return pesel.matches("^[0-9]*$");
a jak biznes wymyśli 3 wymagania:
- użytkownik musi być pełnoletni
- użytkownik musi być urodzony przed rokiem 2000
- użytkownik nie może mieć mniej niż 20 lat

to będą 3 ify? co najmniej 3 przypadki testowe - na pewno

2023-04-15 19:20 UTC, karolukasik commented on class-practice/src/main/java/com/karolina/tuesdaystasks/peselnumber/util/StringUtils.java
> +        return 10 * decimalNumber + onesNumber;
Doobra nie popisuj się xD

2023-04-24 11:00 UTC, Jonarzz approved these changes

2023-04-24 12:14 UTC, merged